### ISSUE TITLE
forking sometime soon

### ISSUE THREAD

**Issue by R3dPhil** [brilliantdrink/hasanabi-census#3]
Hey man thanks for the website. Im gonna fork it for [yugopnik](https://www.twitch.tv/yugopniktwitch) :P sometime soon. Might be this afternoon might be in a year. Just letting you know

**Comment by R3dPhil** [comment]
update i started. How did you do the text. Im not sure its working like i want it to on my fork. also i replaced the svg it somehow isnt working either on the website (i replaced it twice, might have replaced 2 different ones tho ...). P.S. I have no experience with this kind of website deployment, I used only html (js, css and php) in my projects.

**Comment by brilliantdrink** [comment]
Happy you enjoy the project!
I'm using a custom build script (see package.json / `npm run build`)
For future reference, please do not use issues for this.
